<%@ Page Title="" Language="C#" MasterPageFile="~/admin.master" AutoEventWireup="true" CodeFile="mantenedorcliente.aspx.cs" Inherits="mantenedorcliente" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p>
    <br />
</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
    DataKeyNames="RUT" DataSourceID="SqlDataSource1" 
    EmptyDataText="No hay registros de datos para mostrar." CellPadding="4" 
        GridLines="None" AutoGenerateDeleteButton="True" ForeColor="Red">
    <AlternatingRowStyle BackColor="White" />
    <Columns>
        <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" />
        <asp:BoundField DataField="RUT" HeaderText="RUT" ReadOnly="True" 
            SortExpression="RUT" />
        <asp:BoundField DataField="NOMBRE" HeaderText="NOMBRE" 
            SortExpression="NOMBRE" />
        <asp:BoundField DataField="APELLIDO" HeaderText="APELLIDO" 
            SortExpression="APELLIDO" />
        <asp:BoundField DataField="DIRECCION" HeaderText="DIRECCION" 
            SortExpression="DIRECCION" />
        <asp:BoundField DataField="CIUDAD" HeaderText="CIUDAD" 
            SortExpression="CIUDAD" />
        <asp:BoundField DataField="TELEFONO" HeaderText="TELEFONO" 
            SortExpression="TELEFONO" />
        <asp:BoundField DataField="EMAIL" HeaderText="EMAIL" SortExpression="EMAIL" />
        <asp:BoundField DataField="TIPO_LICENCIA" HeaderText="TIPO_LICENCIA" 
            SortExpression="TIPO_LICENCIA" />
    </Columns>
    <EditRowStyle BackColor="#7C6F57" />
    <FooterStyle BackColor="#1C5E55" ForeColor="White" Font-Bold="True" />
    <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
    <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
    <RowStyle BackColor="#E3EAEB" />
    <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
    <SortedAscendingCellStyle BackColor="#F8FAFA" />
    <SortedAscendingHeaderStyle BackColor="#246B61" />
    <SortedDescendingCellStyle BackColor="#D4DFE1" />
    <SortedDescendingHeaderStyle BackColor="#15524A" />
</asp:GridView>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" 
    ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
    DeleteCommand="DELETE FROM [CLIENTE] WHERE [RUT] = @RUT" 
    InsertCommand="INSERT INTO [CLIENTE] ([RUT], [NOMBRE], [APELLIDO], [DIRECCION], [CIUDAD], [TELEFONO], [EMAIL], [TIPO_LICENCIA]) VALUES (@RUT, @NOMBRE, @APELLIDO, @DIRECCION, @CIUDAD, @TELEFONO, @EMAIL, @TIPO_LICENCIA)" 
    ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" 
    SelectCommand="SELECT [RUT], [NOMBRE], [APELLIDO], [DIRECCION], [CIUDAD], [TELEFONO], [EMAIL], [TIPO_LICENCIA] FROM [CLIENTE]" 
    UpdateCommand="UPDATE [CLIENTE] SET [NOMBRE] = @NOMBRE, [APELLIDO] = @APELLIDO, [DIRECCION] = @DIRECCION, [CIUDAD] = @CIUDAD, [TELEFONO] = @TELEFONO, [EMAIL] = @EMAIL, [TIPO_LICENCIA] = @TIPO_LICENCIA WHERE [RUT] = @RUT">
    <DeleteParameters>
        <asp:Parameter Name="RUT" Type="String" />
    </DeleteParameters>
    <InsertParameters>
        <asp:Parameter Name="RUT" Type="String" />
        <asp:Parameter Name="NOMBRE" Type="String" />
        <asp:Parameter Name="APELLIDO" Type="String" />
        <asp:Parameter Name="DIRECCION" Type="String" />
        <asp:Parameter Name="CIUDAD" Type="String" />
        <asp:Parameter Name="TELEFONO" Type="String" />
        <asp:Parameter Name="EMAIL" Type="String" />
        <asp:Parameter Name="TIPO_LICENCIA" Type="String" />
    </InsertParameters>
    <UpdateParameters>
        <asp:Parameter Name="NOMBRE" Type="String" />
        <asp:Parameter Name="APELLIDO" Type="String" />
        <asp:Parameter Name="DIRECCION" Type="String" />
        <asp:Parameter Name="CIUDAD" Type="String" />
        <asp:Parameter Name="TELEFONO" Type="String" />
        <asp:Parameter Name="EMAIL" Type="String" />
        <asp:Parameter Name="TIPO_LICENCIA" Type="String" />
        <asp:Parameter Name="RUT" Type="String" />
    </UpdateParameters>
</asp:SqlDataSource>
<p>
    &nbsp;</p>
<p>
</p>
<p>
</p>
<p>
</p>
<p>
</p>
</asp:Content>

